language: node_js
node_js:
- node
- '6'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: s3
  access_key_id:
    secure: 2RQ89hBjlSnjEdyLsQpvl3RjOK3S8CLAJZUzGKcsdoslIdYaqVGazLR6PkYdNNqVbO9RNjVh1NNvuA+guzSY86NmCW8Ex86pzJP2ANPUyTSYxvoTZGalPzDGk1+hg7yJgRLioAX8AKp8gWc6rTXE8snl6fskvYeQBTQVB5R1O83g//azO2zva857W18sQ2egELRNrnqn0yJX8zt6JGTXA6CXSjjjzjiS5g1Rbyr0/Eai57WOAJlFz7a/via2A7XsRb8P70oA1Ky1NxBN0hJrWj+ZhzgNrbCB1j8BMDHOlGu2ZsbIHvFtV3RV9U9MwhbIRXqlJMZQUjlA7tto2fwqooppTGvooukhZdyzG4mwT2Jl+t9DeqecbOuloqrHbdqmbBCkFi2d6Kt1imZLlj3GpUDyTMFs7B9i9Cu+oJxR3eqcP63qDUXLnZEypZofv1wMw3AFBkFandl0eqjZQNbgp94/z7ofLWDCOUNVZWB556i3VdRM5az8mfwjfFVDDBJqEbg48cSj+wE2vtQ0dBWDb+nXhTQROlxIBCFxoDIDOCopr4Rqf9IhoHz1yBXEeWWvDANq1oMP2pTT1b6+IpmnUB4SKhfgOWYJDOqmGqF1JulM0GFtHUBEethbWBkOLOap/BaXw93gYLIKZbuuuSIVQhKExvTdiOb3hOeCUWlVNkc=
  secret_access_key:
    secure: wan/cjWPFH1kcspHub5mFA00I1yps1Ed3BeqRp3xBSMOlqh4PEEGAqRpwVdCyq4woMk/x4A6RphJVdL2n+rxpQK1feiWhuEcQI9dW9lOErNCAkfk6ioYsigg9uORK0HAJ0yFvMy+j9CCerds2nyLz1YHKj+8tzaTQQP2vFWGyjbFSXfaZthiGre7WpbYyrMwUi3Lbbg8t1jeFC/wJXlZUL5wsGQz+a/+RAG/PRZ6c/qBa40bKoXSpVk555QMci8V9LjNXorIRbscqFvo2JI3qI/q9vni7tLi9ApSBvITOl9VQDUNbJ8WAxpA4Zk0zrCOpgQHJ4bxbH/8jgIShcMatCoLo50hwLUGnsAdVu6TUqnxbobi0HGvNGxQioIHTLV+lFO52zV8fbQ61O5iz/dkgka7VrJcaVQrRevlg74BpOy9t+Gr21Oq8GhJotEvcTn5aG86BaA6LARjnX9XiPbbrm4oNXqbceHKR+0cFDPw7xVZ6KWSAZyn/MReULtWRb55k596DIlJM90T6Yjnlj/KbbmQXvBcm/jvERud/Ch1JGqCnzmctiQ9pKCeCCcIfB7B5g7+yWvfQo+N9we6r7aui3tTvlKSBKf7zvfE19FN2efe3At4Av+ggw+w6fqWBaoCPe9Qc1uA6R46KmpxvW+6fVB9aut9m1pZjL8U76eYNng=
  bucket: www.alecdibble.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
